KEY_CODE(KC_UNASSIGNED, 0x00)
KEY_CODE(KC_ESCAPE, 0x01)
KEY_CODE(KC_1, 0x02)
KEY_CODE(KC_2, 0x03)
KEY_CODE(KC_3, 0x04)
KEY_CODE(KC_4, 0x05)
KEY_CODE(KC_5, 0x06)
KEY_CODE(KC_6, 0x07)
KEY_CODE(KC_7, 0x08)
KEY_CODE(KC_8, 0x09)
KEY_CODE(KC_9, 0x0A)
KEY_CODE(KC_0, 0x0B)
KEY_CODE(KC_MINUS, 0x0C)    //-onmainkeyboard
KEY_CODE(KC_EQUALS, 0x0D)
KEY_CODE(KC_BACK, 0x0E)    //backspace
KEY_CODE(KC_TAB, 0x0F)
KEY_CODE(KC_Q, 0x10)
KEY_CODE(KC_W, 0x11)
KEY_CODE(KC_E, 0x12)
KEY_CODE(KC_R, 0x13)
KEY_CODE(KC_T, 0x14)
KEY_CODE(KC_Y, 0x15)
KEY_CODE(KC_U, 0x16)
KEY_CODE(KC_I, 0x17)
KEY_CODE(KC_O, 0x18)
KEY_CODE(KC_P, 0x19)
KEY_CODE(KC_LBRACKET, 0x1A)
KEY_CODE(KC_RBRACKET, 0x1B)
KEY_CODE(KC_RETURN, 0x1C)    //Enteronmainkeyboard
KEY_CODE(KC_LCONTROL, 0x1D)
KEY_CODE(KC_A, 0x1E)
KEY_CODE(KC_S, 0x1F)
KEY_CODE(KC_D, 0x20)
KEY_CODE(KC_F, 0x21)
KEY_CODE(KC_G, 0x22)
KEY_CODE(KC_H, 0x23)
KEY_CODE(KC_J, 0x24)
KEY_CODE(KC_K, 0x25)
KEY_CODE(KC_L, 0x26)
KEY_CODE(KC_SEMICOLON, 0x27)
KEY_CODE(KC_APOSTROPHE, 0x28)
KEY_CODE(KC_GRAVE, 0x29)    //accent
KEY_CODE(KC_LSHIFT, 0x2A)
KEY_CODE(KC_BACKSLASH, 0x2B)
KEY_CODE(KC_Z, 0x2C)
KEY_CODE(KC_X, 0x2D)
KEY_CODE(KC_C, 0x2E)
KEY_CODE(KC_V, 0x2F)
KEY_CODE(KC_B, 0x30)
KEY_CODE(KC_N, 0x31)
KEY_CODE(KC_M, 0x32)
KEY_CODE(KC_COMMA, 0x33)
KEY_CODE(KC_PERIOD, 0x34)    //.onmainkeyboard
KEY_CODE(KC_SLASH, 0x35)    ///onmainkeyboard
KEY_CODE(KC_RSHIFT, 0x36)
KEY_CODE(KC_MULTIPLY, 0x37)    //*onnumerickeypad
KEY_CODE(KC_LMENU, 0x38)    //leftAlt
KEY_CODE(KC_SPACE, 0x39)
KEY_CODE(KC_CAPITAL, 0x3A)
KEY_CODE(KC_F1, 0x3B)
KEY_CODE(KC_F2, 0x3C)
KEY_CODE(KC_F3, 0x3D)
KEY_CODE(KC_F4, 0x3E)
KEY_CODE(KC_F5, 0x3F)
KEY_CODE(KC_F6, 0x40)
KEY_CODE(KC_F7, 0x41)
KEY_CODE(KC_F8, 0x42)
KEY_CODE(KC_F9, 0x43)
KEY_CODE(KC_F10, 0x44)
KEY_CODE(KC_NUMLOCK, 0x45)
KEY_CODE(KC_SCROLL, 0x46)    //ScrollLock
KEY_CODE(KC_NUMPAD7, 0x47)
KEY_CODE(KC_NUMPAD8, 0x48)
KEY_CODE(KC_NUMPAD9, 0x49)
KEY_CODE(KC_SUBTRACT, 0x4A)    //-onnumerickeypad
KEY_CODE(KC_NUMPAD4, 0x4B)
KEY_CODE(KC_NUMPAD5, 0x4C)
KEY_CODE(KC_NUMPAD6, 0x4D)
KEY_CODE(KC_ADD, 0x4E)    //+onnumerickeypad
KEY_CODE(KC_NUMPAD1, 0x4F)
KEY_CODE(KC_NUMPAD2, 0x50)
KEY_CODE(KC_NUMPAD3, 0x51)
KEY_CODE(KC_NUMPAD0, 0x52)
KEY_CODE(KC_DECIMAL, 0x53)    //.onnumerickeypad
KEY_CODE(KC_OEM_102, 0x56)    //<>|onUK/Germanykeyboards
KEY_CODE(KC_F11, 0x57)
KEY_CODE(KC_F12, 0x58)
KEY_CODE(KC_F13, 0x64)    //(NECPC98)
KEY_CODE(KC_F14, 0x65)    //(NECPC98)
KEY_CODE(KC_F15, 0x66)    //(NECPC98)
KEY_CODE(KC_KANA, 0x70)    //(Japanesekeyboard)
KEY_CODE(KC_ABNT_C1, 0x73)    ///?onPortugese(Brazilian)keyboards
KEY_CODE(KC_CONVERT, 0x79)    //(Japanesekeyboard)
KEY_CODE(KC_NOCONVERT, 0x7B)    //(Japanesekeyboard)
KEY_CODE(KC_YEN, 0x7D)    //(Japanesekeyboard)
KEY_CODE(KC_ABNT_C2, 0x7E)    //Numpad.onPortugese(Brazilian)keyboards
KEY_CODE(KC_NUMPADEQUALS, 0x8D)    //, onnumerickeypad(NECPC98)
KEY_CODE(KC_PREVTRACK, 0x90)    //PreviousTrack(KEY_CODE(KC_CIRCUMFLEXonJapanesekeyboard)
KEY_CODE(KC_AT, 0x91)    //(NECPC98)
KEY_CODE(KC_COLON, 0x92)    //(NECPC98)
KEY_CODE(KC_UNDERLINE, 0x93)    //(NECPC98)
KEY_CODE(KC_KANJI, 0x94)    //(Japanesekeyboard)
KEY_CODE(KC_STOP, 0x95)    //(NECPC98)
KEY_CODE(KC_AX, 0x96)    //(JapanAX)
KEY_CODE(KC_UNLABELED, 0x97)    //(J3100)
KEY_CODE(KC_NEXTTRACK, 0x99)    //NextTrack
KEY_CODE(KC_NUMPADENTER, 0x9C)    //Enteronnumerickeypad
KEY_CODE(KC_RCONTROL, 0x9D)
KEY_CODE(KC_MUTE, 0xA0)    //Mute
KEY_CODE(KC_CALCULATOR, 0xA1)    //Calculator
KEY_CODE(KC_PLAYPAUSE, 0xA2)    //Play/Pause
KEY_CODE(KC_MEDIASTOP, 0xA4)    //MediaStop
KEY_CODE(KC_VOLUMEDOWN, 0xAE)    //Volume-
KEY_CODE(KC_VOLUMEUP, 0xB0)    //Volume+
KEY_CODE(KC_WEBHOME, 0xB2)    //Webhome
KEY_CODE(KC_NUMPADCOMMA, 0xB3)    //)onnumerickeypad(NECPC98)
KEY_CODE(KC_DIVIDE, 0xB5)    ///onnumerickeypad
KEY_CODE(KC_SYSRQ, 0xB7)
KEY_CODE(KC_RMENU, 0xB8)    //rightAlt
KEY_CODE(KC_PAUSE, 0xC5)    //Pause
KEY_CODE(KC_HOME, 0xC7)    //Homeonarrowkeypad
KEY_CODE(KC_UP, 0xC8)    //UpArrowonarrowkeypad
KEY_CODE(KC_PGUP, 0xC9)    //PgUponarrowkeypad
KEY_CODE(KC_LEFT, 0xCB)    //LeftArrowonarrowkeypad
KEY_CODE(KC_RIGHT, 0xCD)    //RightArrowonarrowkeypad
KEY_CODE(KC_END, 0xCF)    //Endonarrowkeypad
KEY_CODE(KC_DOWN, 0xD0)    //DownArrowonarrowkeypad
KEY_CODE(KC_PGDOWN, 0xD1)    //PgDnonarrowkeypad
KEY_CODE(KC_INSERT, 0xD2)    //Insertonarrowkeypad
KEY_CODE(KC_DELETE, 0xD3)    //Deleteonarrowkeypad
KEY_CODE(KC_LWIN, 0xDB)    //LeftWindowskey
KEY_CODE(KC_RWIN, 0xDC)    //RightWindowskey
KEY_CODE(KC_APPS, 0xDD)    //AppMenukey
KEY_CODE(KC_POWER, 0xDE)    //SystemPower
KEY_CODE(KC_SLEEP, 0xDF)    //SystemSleep
KEY_CODE(KC_WAKE, 0xE3)    //SystemWake
KEY_CODE(KC_WEBSEARCH, 0xE5)    //WebSearch
KEY_CODE(KC_WEBFAVORITES, 0xE6)    //WebFavorites
KEY_CODE(KC_WEBREFRESH, 0xE7)    //WebRefresh
KEY_CODE(KC_WEBSTOP, 0xE8)    //WebStop
KEY_CODE(KC_WEBFORWARD, 0xE9)    //WebForward
KEY_CODE(KC_WEBBACK, 0xEA)    //WebBack
KEY_CODE(KC_MYCOMPUTER, 0xEB)    //MyComputer
KEY_CODE(KC_MAIL, 0xEC)    //Mail
KEY_CODE(KC_MEDIASELECT, 0xED)    //Media Select