/// @file
/// Definitions related to the current platform.

#ifndef Platform_h__
#define Platform_h__

#ifdef _WIN32
	#define __WIN__
#else
	#define __UNIX__
#endif


#ifdef __WIN__
// Disable warning 'conditional expression is constant'. The compiler will optimize it away.
#pragma warning(disable: 4127)
// Disable warning 'unreferenced formal parameters'. We always want formal parameters to be present!
#pragma warning(disable: 4100)
// Disable warning 'assignment operator could not be generated'. We don't want autogenerated assignment operators!
#pragma warning(disable: 4512)
// Disable MSVC warnings about use of 'unsafe' functions like strcpy().
#define _CRT_SECURE_NO_WARNINGS
#endif


#endif // Platform_h__