#ifndef _ENTITYMESSAGE_H_
#define _ENTITYMESSAGE_H_

namespace EntitySystem
{

	/// @name Message is the only way how to pass/get some data from/to an entity.
	struct EntityMessage
	{
		enum eResult { RESULT_IGNORED, RESULT_OK, RESULT_ERROR };

		/// @name Define user types of messages here.
		enum eType
		{ 
			TYPE_DRAW_PLATFORM=0,
			TYPE_DRAW_PLATFORM_LINK,
			TYPE_DRAW_PLATFORM_ITEM,
			TYPE_DRAW_PROJECTILE,
			TYPE_DRAW_UNDERLAY,
			TYPE_DRAW_OVERLAY,
			TYPE_UPDATE_PHYSICS_SERVER,
			TYPE_UPDATE_PHYSICS_CLIENT,
			TYPE_GET_POSITION,
			TYPE_GET_BODY_POSITION,
			TYPE_GET_RELATIVE_POSITION,
			TYPE_GET_ANGLE,
			TYPE_GET_RELATIVE_ANGLE,
			TYPE_GET_ARC_ANGLE,
			TYPE_GET_POLYSHAPE,
			TYPE_GET_DURABILITY_RATIO,
			TYPE_GET_DENSITY,
			TYPE_GET_MAX_HITPOINTS,
			TYPE_GET_HITPOINTS,
			TYPE_GET_MAX_POWER,
			TYPE_GET_POWER_RATIO,
			TYPE_GET_PHYSICS_BODY,
			TYPE_GET_BLUEPRINTS,
			TYPE_GET_MATERIAL,
			TYPE_GET_PARENT,
			TYPE_GET_STABILIZATION_RATIO,
			TYPE_GET_TEXTURE,
			TYPE_GET_TEXTURE_ANGLE,
			TYPE_GET_TEXTURE_SCALE,
			TYPE_GET_EFFECT,
			TYPE_GET_EFFECT_SCALE,
			TYPE_GET_RESOURCE_GROUP,
			TYPE_SET_ANGLE,
			TYPE_SET_RELATIVE_ANGLE,
			TYPE_SET_POWER_RATIO,
			TYPE_ADD_PLATFORM,
			TYPE_REMOVE_PLATFORM,
			TYPE_DETACH_PLATFORM,
			TYPE_ADD_PLATFORM_ITEM,
			TYPE_MOUSE_PICK,
			TYPE_LINK_PLATFORMS,
			TYPE_LINKS_PLATFORM, // question
			TYPE_UNLINK_PLATFORM,
			TYPE_PHYSICS_UPDATE_MASS,
			TYPE_START_SHOOTING,
			TYPE_STOP_SHOOTING,
			TYPE_STRIKE,
			TYPE_DAMAGE,
			TYPE_KNOCKBACK_DETACH,
			TYPE_EXPLOSION,
			TYPE_UPDATE_TEAM,
			TYPE_DIE,
			TYPE_POST_INIT,

			NUM_TYPES
		};
		eType type;
		void* data;

		EntityMessage(eType _type): type(_type), data(0) {}
		EntityMessage(eType _type, void* _data): type(_type), data(_data) {}
	};
}

#endif