// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate
// it is important that you use premake recreate this file if changing xml parsers or codecs for the static builds
#define CEGUI_WITH_EXPAT 1
#define CEGUI_SAMPLES_USE_IRRLICHT 
#define CEGUI_SAMPLES_USE_DIRECTX_9 
#define CEGUI_LOAD_MODULE_DEBUG_SUFFIX "_d"
#define CEGUI_SAMPLES_USE_DIRECTX_10 
#define CEGUI_SAMPLES_USE_OGRE 
#define CEGUI_DEFAULT_XMLPARSER ExpatParser
#define CEGUI_HAS_FREETYPE 
#define CEGUI_USE_MINIBIDI 
#define CEGUI_BIDI_SUPPORT 
#define CEGUI_HAS_DEFAULT_LOGGER 
#define CEGUI_CODEC_SILLY 1
#define CEGUI_DEFAULT_IMAGE_CODEC SILLYImageCodec
#define CEGUI_IRR_SDK_VERSION 16
#define CEGUI_LOAD_MODULE_APPEND_SUFFIX_FOR_DEBUG 1
#define CEGUI_SAMPLES_USE_OPENGL 
#define CEGUI_FALAGARD_RENDERER 
#define CEGUI_TINYXML_H "ceguitinyxml/tinyxml.h"
#define CEGUI_LUA_VER 51
#define CEGUI_HAS_PCRE_REGEX 
#define CEGUI_TINYXML_NAMESPACE CEGUITinyXML
