

/// @name Here are defined types for all entities in the game. The macro used for definition is inside EntityEnums.h.
//@{

COMPONENT_TYPE(CT_PLATFORM_LOGIC)
COMPONENT_TYPE(CT_PLATFORM_PARAMS)
COMPONENT_TYPE(CT_PLATFORM_PHYSICS)
COMPONENT_TYPE(CT_PLATFORM_VISUAL)
COMPONENT_TYPE(CT_PLATFORM_LINKS)
COMPONENT_TYPE(CT_MATERIAL)
COMPONENT_TYPE(CT_SHIP_LOGIC)
COMPONENT_TYPE(CT_SHIP_PHYSICS)
COMPONENT_TYPE(CT_SHIP_VISUAL)
COMPONENT_TYPE(CT_PLATFORM_ITEM)
COMPONENT_TYPE(CT_ENGINE_PARAMS)
COMPONENT_TYPE(CT_ENGINE)

//@}
