/// @file
/// Here are definitions of types for all entity components in the game. The macro used for definition is inside ComponentEnums.h.

COMPONENT_TYPE(CT_PLATFORM_LOGIC, CmpPlatformLogic)
COMPONENT_TYPE(CT_PLATFORM_PARAMS, CmpPlatformParams)
COMPONENT_TYPE(CT_PLATFORM_PHYSICS, CmpPlatformPhysics)
COMPONENT_TYPE(CT_PLATFORM_VISUAL, CmpPlatformVisual)
COMPONENT_TYPE(CT_PLATFORM_LINKS, CmpPlatformLinks)
COMPONENT_TYPE(CT_MATERIAL, CmpMaterial)
COMPONENT_TYPE(CT_SHIP_LOGIC, CmpShipLogic)
COMPONENT_TYPE(CT_SHIP_PHYSICS, CmpShipPhysics)
COMPONENT_TYPE(CT_SHIP_VISUAL, CmpShipVisual)
COMPONENT_TYPE(CT_PLATFORM_ITEM, CmpPlatformItem)
COMPONENT_TYPE(CT_PLATFORM_ITEM_PARAMS, CmpPlatformItemParams)
COMPONENT_TYPE(CT_ENGINE_PARAMS, CmpEngineParams)
COMPONENT_TYPE(CT_ENGINE, CmpEngine)
COMPONENT_TYPE(CT_WEAPON_PARAMS, CmpWeaponParams)
COMPONENT_TYPE(CT_WEAPON, CmpWeapon)
COMPONENT_TYPE(CT_AMMO_PARAMS, CmpAmmoParams)
COMPONENT_TYPE(CT_PROJECTILE, CmpProjectile)


